# Generated by Django 5.0.2 on 2024-10-25 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_status', models.IntegerField(default=0)),
                ('type_proc', models.IntegerField(default=0)),
                ('dogovor', models.CharField(blank=True, max_length=10)),
                ('n_order', models.CharField(blank=True, max_length=12)),
                ('street', models.CharField(max_length=30)),
                ('build', models.CharField(max_length=10)),
                ('kv', models.CharField(blank=True, max_length=6)),
                ('fio', models.CharField(blank=True, max_length=320)),
                ('prim', models.CharField(blank=True, max_length=180)),
                ('comment', models.CharField(blank=True, max_length=360)),
                ('resource', models.CharField(blank=True, max_length=2048)),
                ('pause_type', models.CharField(blank=True, max_length=40)),
                ('box_port', models.IntegerField(default=0)),
                ('man_oper', models.CharField(blank=True, max_length=30)),
                ('man_install', models.CharField(blank=True, max_length=30)),
                ('date_1', models.DateTimeField(default=datetime.datetime.now)),
                ('date_2', models.DateTimeField(default=datetime.datetime.now)),
                ('date_3', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
