# Generated by Django 5.0.2 on 2024-10-25 12:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Device_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Energy_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=20)),
                ('lo', models.BooleanField(default=False)),
                ('rent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lo', models.BooleanField(default=False)),
                ('obj', models.BooleanField(default=False)),
                ('coup', models.BooleanField(default=False)),
                ('rent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('time_rec', models.DateTimeField(default=datetime.datetime.now)),
                ('obj_type', models.IntegerField(default=0)),
                ('obj_id', models.IntegerField(default=0)),
                ('operation1', models.IntegerField(default=0)),
                ('operation2', models.IntegerField(default=0)),
                ('text', models.CharField(blank=True, max_length=2560)),
            ],
        ),
        migrations.CreateModel(
            name='last_visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=128)),
                ('date_l_v', models.DateTimeField(default=datetime.datetime.now)),
                ('prim', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='manage_comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('info', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='map_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_adm', '_admin_'), ('can_new', '_create_new_'), ('can_del', '_delete_object_'), ('can_edit', '_edit_object_'), ('can_edit_bu', '_edit_build_'), ('can_edit_en', '_edit_energy_'), ('can_ext', '_ext_cross_'), ('can_int', '_int_cross_'), ('can_ab', '_abonent_app_'), ('can_sh_agr', '_show_agr_'), ('can_app_view', '_app_view_'), ('can_app_edit', '_app_edit_'), ('can_cable_edit', '_cable_edit_')),
            },
        ),
        migrations.CreateModel(
            name='Subunit_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Templ_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('units', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Templ_box_cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ports', models.IntegerField(default=0)),
                ('alias_list', models.CharField(max_length=300)),
                ('num_plints', models.IntegerField(default=0)),
                ('color_cable', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Templ_cross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ports', models.IntegerField(default=0)),
                ('port_t_x', models.IntegerField(default=1)),
                ('v_col', models.IntegerField(default=1)),
                ('v_row', models.IntegerField(default=1)),
                ('v_forw_l_r', models.BooleanField(default=True)),
                ('ext_p', models.BooleanField(default=False)),
                ('units', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Templ_locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Templ_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ports', models.IntegerField(default=0)),
                ('port_alias_list', models.CharField(max_length=2000)),
                ('port_t_x_list', models.CharField(max_length=2000)),
                ('port_speed_list', models.CharField(max_length=2000)),
                ('units', models.IntegerField(default=1)),
                ('parrent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.device_type')),
            ],
        ),
        migrations.CreateModel(
            name='Templ_subunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('parrent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.subunit_type')),
            ],
        ),
    ]
