# Generated by Django 4.1.12 on 2023-12-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_visit',
            name='fullname',
            field=models.CharField(max_length=128),
        ),
    ]
