# Generated by Django 4.0.2 on 2023-05-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cross', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parrent', models.IntegerField(default=0)),
                ('parr_type', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=40)),
                ('name_type', models.CharField(max_length=30)),
                ('object_owner', models.CharField(blank=True, max_length=60)),
                ('installed', models.BooleanField(default=True)),
                ('date_ent', models.DateField(blank=True, null=True)),
                ('rasp', models.CharField(blank=True, max_length=200)),
                ('prim', models.CharField(blank=True, max_length=200)),
                ('coord_x', models.FloatField(default=0)),
                ('coord_y', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4096)),
                ('pos', models.CharField(max_length=15)),
                ('color1', models.CharField(max_length=7)),
                ('color2', models.CharField(max_length=7)),
                ('param', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineidid', models.CharField(max_length=15)),
                ('linecncn', models.CharField(max_length=15)),
                ('cabtype', models.CharField(max_length=64)),
                ('cabcolor', models.CharField(max_length=7)),
                ('path', models.CharField(max_length=4096)),
                ('param', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Templ_cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('capacity', models.IntegerField(default=0)),
                ('modules', models.IntegerField(default=0)),
                ('mod_capa_list', models.CharField(blank=True, max_length=1024)),
                ('mod_color_list', models.CharField(blank=True, max_length=1024)),
                ('fiber_colors_list', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Templ_coupling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='PW_cont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('obj_type', models.IntegerField(default=0)),
                ('object_owner', models.CharField(blank=True, max_length=60)),
                ('rasp', models.CharField(blank=True, max_length=200)),
                ('prim', models.CharField(blank=True, max_length=200)),
                ('coord_x', models.FloatField(default=0)),
                ('coord_y', models.FloatField(default=0)),
                ('parrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross.kvartal')),
            ],
        ),
        migrations.CreateModel(
            name='Coupling_ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_num', models.IntegerField(default=0)),
                ('cable_type', models.IntegerField(default=0)),
                ('fiber_num', models.IntegerField(default=0)),
                ('fiber_color', models.CharField(blank=True, max_length=16)),
                ('mod_num', models.IntegerField(default=0)),
                ('mod_color', models.CharField(blank=True, max_length=16)),
                ('p_valid', models.BooleanField(default=True)),
                ('changed', models.BooleanField(default=False)),
                ('prim', models.CharField(blank=True, max_length=200)),
                ('up_id', models.IntegerField(default=0)),
                ('up_info', models.CharField(blank=True, max_length=256)),
                ('int_c_dest', models.IntegerField(default=0)),
                ('int_c_id', models.IntegerField(default=0)),
                ('int_c_status', models.IntegerField(default=0)),
                ('parrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable.coupling')),
            ],
        ),
    ]
