# Generated by Django 4.0.2 on 2023-06-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cross',
            name='parrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cross.locker'),
        ),
    ]
