# Generated by Django 5.0.2 on 2025-12-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='kv_count',
            field=models.IntegerField(default=0),
        ),
    ]
