# Generated by Django 4.0.2 on 2023-06-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0002_alter_cross_parrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='parrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cross.locker'),
        ),
        migrations.AlterField(
            model_name='building',
            name='parrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cross.street'),
        ),
        migrations.AlterField(
            model_name='device',
            name='parrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cross.locker'),
        ),
        migrations.AlterField(
            model_name='locker',
            name='parrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cross.building'),
        ),
        migrations.AlterField(
            model_name='subunit',
            name='parrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cross.locker'),
        ),
    ]
