# Generated by Django 4.0.10 on 2023-07-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cross', '0003_alter_box_parrent_alter_building_parrent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='obj_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.templ_device'),
        ),
    ]
