# Generated by Django 4.1.12 on 2023-12-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0004_device_obj_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='double_id',
            field=models.IntegerField(default=0),
        ),
    ]
