# Generated by Django 4.1.12 on 2023-12-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0005_building_double_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='double',
        ),
        migrations.RemoveField(
            model_name='building',
            name='double_list',
        ),
    ]
