# Generated by Django 4.1.12 on 2024-01-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0007_remove_device_con_type_remove_device_name_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_gateway',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='device',
            name='ip_mask',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='vlan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device_ports',
            name='vlantz',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
